nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs

npmScopes:
  core:
    npmAlwaysAuth: true
    npmAuthIdent: '${AZURE_DEVOPS_PAT:-fallback}'
    npmRegistryServer: 'https://pkgs.dev.azure.com/smartcraftsoftware/_packaging/smartcraftsoftware/npm/registry/'

npmRegistryServer: 'https://registry.npmjs.org'
